; Override pm.max_children=5 из дефолтного пула nextcloud:33-fpm.
; Префикс zzz- в имени файла гарантирует загрузку после www.conf и zz-docker.conf.

[www]
pm = dynamic
pm.max_children = 30
pm.start_servers = 8
pm.min_spare_servers = 4
pm.max_spare_servers = 12
